name: oc-backend-api
namespace: ffisa-dev

image:
  repository: fabricioph2/oc-backend-api
  tag: "{{ tag }}"

replicas: 1

resources:
  requests:
    cpu: "200m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

service:
  enabled: true
  port: 80
  targetPort: 3000

route:
  enabled: true
  host: ""

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5

statefulset:
  enabled: false

env:
  - name: DATA_API_URL
    value: "http://oc-backend-data:80"

networkPolicies:
  enabled: true
